# [START runtime]
env_variables:
  ENVIRONMENT: PROD
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

beta_settings:
    cloud_sql_instances: autointern-prod:us-east1:autointern-prod
#autointern-196523:us-east1:terndb1

runtime_config:
  python_version: 3
# [END runtime]
