version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers

    working_directory: ~/AutoIntern-Django
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: Set Up GOOGLE_CLOUD_DEFAULT_CREDENTIALS
          command: |
            echo $CLIENT_SECRET | base64 -di > /tmp/client_secret.json

      - run:
          name: run tests
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS="/tmp/client_secret.json"
            . venv/bin/activate
            ./cloud_sql_proxy_linux -instances="autointern-196523:us-east1:terndb1"=tcp:5432 &
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
